cronjob:
  schedule: "@daily"
  priorityClassName: ""
  ttlSecondsAfterFinished: 7776000
outputFormat: gratia
gridSecurityHostPath: true
pspName: ""
user:
  uid: 10000
  gid: 10000
dataVolumeSize: 1000M
containerSecurityContext:
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
processor:
  # image_repository: "hub.opensciencegrid.org/osgpreview/kuantifier-processor"
  # image_tag: "1.0.3-rc3"
  image_repository: "docker.io/samunldocker/kapeldev"
  image_tag: "latest"
  image_pull_policy: "Always"
  # image_repository: "hub.opensciencegrid.org/osgpreview/kapel-processor"
  # image_tag: "latest"
  # image_pull_policy: "IfNotPresent"
  resources:
    limits:
      cpu: "1"
      memory: "2000Mi"
    requests:
      cpu: "0.5"
      memory: "500Mi"
  config:
    SITE_NAME: "coffea-casa-cms"
    SUBMIT_HOST: "coffea.casa"
    NAMESPACE: "cmsaf-prod"
    VO_NAME: "cms"
    PROMETHEUS_SERVER: "http://10.97.42.129:9090"
    GRID: "OSG"
ssmsend:
  resources:
    limits:
      cpu: "0.5"
      memory: "500Mi"
    requests:
      cpu: "0.1"
      memory: "50Mi"
  enabled: true
  image_repository: "git.computecanada.ca:4567/rptaylor/misc/ssmsend"
  image_tag: ""
  host: "msg.argo.grnet.gr"
  x509cert: aW5zZXJ0IGJhc2U2NC1lbmNvZGVkIHN0cmluZyBvZiB0aGUgWDUwOSBwdWJsaWMgY2VydCBmb3IgQVBFTCBwdWJsaXNoZXIK
  x509key: aW5zZXJ0IGJhc2U2NC1lbmNvZGVkIHN0cmluZyBvZiB0aGUgWDUwOSBwcml2YXRlIGtleSBmb3IgQVBFTCBwdWJsaXNoZXIK
gratia:
  resources:
    limits:
      cpu: "0.5"
      memory: "500Mi"
    requests:
      cpu: "0.1"
      memory: "50Mi"
  image_repository: "hub.opensciencegrid.org/osgpreview/kapel-gratia-output"
  image_tag: ""
  config:
    GRATIA_CONFIG_PATH: "/etc/gratia/kubernetes/ProbeConfig"
nameOverride: ""
fullnameOverride: ""